name = "reference"
defaultTargets = ["contextful-reference"]

[[lean_lib]]
name = "Reference"

[[lean_exe]]
name = "contextful-reference"
root = "Main"

[[lean_lib]]
name = "Contextful"
srcDir = ".."
