//! `spec/cards/<contract>.md`: one generated page per contract — its operations with
//! their ledes, its refusals and its bounds, each naming the clause that owns it.

use crate::corpus::*;
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// Every contract's card, keyed by contract name.
pub fn pages(c: &Corpus) -> BTreeMap<String, String> {
    c.reg.contracts.keys().map(|name| (name.clone(), format!("{}\n", page(c, name).trim_end()))).collect()
}

fn page(c: &Corpus, contract: &str) -> String {
    let entry = &c.reg.contracts[contract];
    let docs: Vec<&Doc> = c.contracts().filter(|d| d.contract.as_deref() == Some(contract)).collect();
    let position: BTreeMap<&str, (usize, usize)> = docs
        .iter()
        .enumerate()
        .flat_map(|(i, d)| d.clauses.iter().map(move |cl| (cl.id.as_str(), (i, cl.line))))
        .collect();
    let mut s = String::new();
    let _ = writeln!(s, "# {} — card\n", entry.title);
    let _ = writeln!(
        s,
        "Generated by `contextful-spec state` from the contract's files and `spec/terms/{contract}.toml`; not authored.\n"
    );

    s.push_str("## Operations\n\n| Operation | Covers | Clauses |\n| --- | --- | --- |\n");
    for d in &docs {
        for op in &d.owns {
            let n = d.clauses.iter().filter(|cl| &cl.operation == op).count();
            let lede = d.ledes.get(op).map(String::as_str).unwrap_or("");
            let _ = writeln!(s, "| `{op}` | {lede} | {n} |");
        }
    }
    s.push('\n');

    let Some(fr) = c.reg.fragments.get(contract) else { return s };
    let order = |clause: &str| position.get(clause).copied().unwrap_or((usize::MAX, 0));

    let mut errors: Vec<(&String, &ErrorEntry)> = fr.error.iter().collect();
    errors.sort_by_key(|(id, e)| (order(&e.clause), id.as_str()));
    if !errors.is_empty() {
        s.push_str("## Refusals\n\n| Error | When | Clause |\n| --- | --- | --- |\n");
        for (id, e) in errors {
            let _ = writeln!(s, "| `{id}` | {} | `{}` |", e.gloss, e.clause);
        }
        s.push('\n');
    }

    let mut limits: Vec<(&String, &LimitEntry)> = fr.limit.iter().collect();
    limits.sort_by_key(|(id, l)| (order(&l.clause), id.as_str()));
    if !limits.is_empty() {
        s.push_str("## Bounds\n\n| Bound | Value | Basis | Clause |\n| --- | --- | --- | --- |\n");
        for (id, l) in limits {
            let _ = writeln!(s, "| `{id}` | {} {} | {} | `{}` |", l.value_text(), l.unit, l.basis, l.clause);
        }
        s.push('\n');
    }
    s
}
