//! `contextful-spec` — the one implementation of every rule `spec/00-corpus.md`
//! states. The gate and a local run invoke the identical command.

mod checks;
mod corpus;
mod util;

use anyhow::Result;
use clap::{Parser, Subcommand};
use corpus::*;
use serde::Serialize;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "contextful-spec", about = "The corpus checker")]
struct Cli {
    /// Repository root holding `spec/`.
    #[arg(long, global = true, default_value = ".")]
    root: PathBuf,
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Run every check, or one named check.
    Lint {
        #[arg(long)]
        check: Option<String>,
        #[arg(long)]
        json: bool,
    },
    /// Write `spec/spec.lock.json`.
    Extract,
    /// Write `spec/status.md` from `spec/pins.toml`.
    State,
    /// Set every contract's coverage floor to its live performed count.
    Pins,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let root = cli.root.canonicalize().unwrap_or(cli.root.clone());
    let c = Corpus::load(&root)?;
    match cli.cmd {
        Cmd::Lint { check, json } => lint(&c, check.as_deref(), json),
        Cmd::Extract => Ok(std::fs::write(root.join("spec/spec.lock.json"), lock_text(&c))?),
        Cmd::State => Ok(std::fs::write(root.join("spec/status.md"), status_text(&c))?),
        Cmd::Pins => raise_floor(&c),
    }
}

fn lint(c: &Corpus, one: Option<&str>, json: bool) -> Result<()> {
    let names: Vec<&str> = match one {
        Some(n) => vec![n],
        None => checks::CHECKS.to_vec(),
    };
    let mut all: Vec<Finding> = Vec::new();
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for n in &names {
        let mut f = checks::run(c, n);
        f.sort_by_key(|a| (a.file.clone(), a.line));
        counts.insert(n, f.len());
        all.append(&mut f);
    }
    if json {
        #[derive(Serialize)]
        struct Report<'a> {
            total: usize,
            counts: &'a BTreeMap<&'a str, usize>,
            findings: &'a [Finding],
        }
        println!("{}", serde_json::to_string_pretty(&Report { total: all.len(), counts: &counts, findings: &all })?);
    } else {
        for f in &all {
            println!("{}:{}  {}  {}", f.file, f.line, f.code, f.message);
        }
        eprintln!("\n--- counts ---");
        for (n, k) in &counts {
            eprintln!("{:<10} {}", n, k);
        }
        eprintln!("{:<10} {}", "TOTAL", all.len());
    }
    if all.is_empty() {
        Ok(())
    } else {
        std::process::exit(1)
    }
}

// ---------------------------------------------------------------- lock

pub fn lock_text(c: &Corpus) -> String {
    #[derive(Serialize)]
    struct Lock<'a> {
        clauses: Vec<&'a Clause>,
        owns: BTreeMap<&'a str, &'a Vec<String>>,
        pointers: Vec<(&'a str, String)>,
        registry: &'a Registry,
    }
    let clauses: Vec<&Clause> = c.clauses().collect();
    let pointers = clauses
        .iter()
        .flat_map(|cl| pointers(&cl.statement).into_iter().map(move |p| (cl.id.as_str(), p)))
        .collect();
    let owns = c.contracts().map(|d| (d.rel.as_str(), &d.owns)).collect();
    let mut s = serde_json::to_string_pretty(&Lock { clauses, owns, pointers, registry: &c.reg }).unwrap();
    s.push('\n');
    s
}

// ---------------------------------------------------------------- status

pub fn status_text(c: &Corpus) -> String {
    let pins = checks::load_pins(c);
    let clauses = c.clause_map();
    let mut s = String::new();
    s.push_str("# Status\n\nGenerated by `contextful-spec state` from `spec/pins.toml`; not authored.\n");
    s.push_str("An unpinned clause is `committed`; a pinned one is `performed` when its artifact resolves under `crates/`, else `broken`.\n\n");
    s.push_str("| Contract | Files | Operations | Clauses | Refusals | Limits | Unsettled | Performed | Broken | Floor |\n");
    s.push_str("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n");
    let mut totals = [0usize; 8];
    for (name, e) in &c.reg.contracts {
        let docs: Vec<&Doc> = c.contracts().filter(|d| d.contract.as_deref() == Some(name)).collect();
        let cls: Vec<&Clause> = docs.iter().flat_map(|d| d.clauses.iter()).collect();
        let ops = c.reg.fragments.get(name).map(|f| f.operation.len()).unwrap_or(0);
        let refusals = cls.iter().filter(|x| x.kind == "refusal").count();
        let limits = cls.iter().filter(|x| x.kind == "limit").count();
        let unsettled = docs.iter().flat_map(|d| d.kinds.iter()).filter(|k| **k == LineKind::Unsettled).count();
        let (mut perf, mut broken) = (0, 0);
        for (id, pin) in &pins.pin {
            if clauses.get(id).map(|x| &x.contract == name).unwrap_or(false) {
                if checks::verdict(c, pin) == "performed" {
                    perf += 1
                } else {
                    broken += 1
                }
            }
        }
        let floor = pins.floor.get(name).copied().unwrap_or(0);
        let row = [e.files.len(), ops, cls.len(), refusals, limits, unsettled, perf, broken];
        for (i, v) in row.iter().enumerate() {
            totals[i] += v;
        }
        let _ = writeln!(
            s,
            "| `{name}` | {} | {} | {} | {} | {} | {} | {} | {} | {floor} |",
            row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7]
        );
    }
    let _ = writeln!(
        s,
        "| **total** | {} | {} | {} | {} | {} | {} | {} | {} | |",
        totals[0], totals[1], totals[2], totals[3], totals[4], totals[5], totals[6], totals[7]
    );
    let records = c.records().count();
    let _ = writeln!(s, "\nDecision records: {records}.\n");
    let (claim, _) = checks::expand_roadmap(c);
    if !claim.is_empty() {
        s.push_str("## Milestones\n\n| Milestone | Operations | Clauses | Performed |\n| --- | --- | --- | --- |\n");
        for (m, _, _) in checks::roadmap(c) {
            let ops: Vec<&String> = claim.iter().filter(|(_, v)| **v == m).map(|(k, _)| k).collect();
            let cls: Vec<&Clause> = c
                .clauses()
                .filter(|cl| ops.iter().any(|o| **o == format!("{}.{}", cl.contract, cl.operation)))
                .collect();
            let perf = cls
                .iter()
                .filter(|cl| pins.pin.get(&cl.id).map(|p| checks::verdict(c, p) == "performed").unwrap_or(false))
                .count();
            let _ = writeln!(s, "| {m} | {} | {} | {perf} |", ops.len(), cls.len());
        }
        let unscheduled = c
            .reg
            .fragments
            .iter()
            .flat_map(|(k, f)| f.operation.keys().map(move |o| format!("{k}.{o}")))
            .filter(|o| !claim.contains_key(o))
            .count();
        let _ = writeln!(s, "\nUnscheduled operations: {unscheduled}.");
    }
    if !pins.pin.is_empty() {
        s.push_str("\n## Pins\n\n| Clause | Verdict |\n| --- | --- |\n");
        for (id, pin) in &pins.pin {
            let _ = writeln!(s, "| `{id}` | {} |", checks::verdict(c, pin));
        }
    }
    s
}

fn raise_floor(c: &Corpus) -> Result<()> {
    let path = c.root.join("spec/pins.toml");
    let text = std::fs::read_to_string(&path).unwrap_or_default();
    let pins = checks::load_pins(c);
    let clauses = c.clause_map();
    let mut live: BTreeMap<String, i64> = c.reg.contracts.keys().map(|k| (k.clone(), 0)).collect();
    for (id, pin) in &pins.pin {
        if let Some(cl) = clauses.get(id) {
            if checks::verdict(c, pin) == "performed" {
                *live.entry(cl.contract.clone()).or_default() += 1;
            }
        }
    }
    let head = text.split("\n[floor]").next().unwrap_or("").trim_end().to_string();
    let mut out = head;
    out.push_str("\n\n[floor]\n");
    for (k, v) in live {
        let _ = writeln!(out, "{k} = {v}");
    }
    std::fs::write(path, out)?;
    Ok(())
}
