//! `spec/targets/<provider>.toml`: one target profile per provider, the checks
//! `corpus.targets` states over them, and the `spec/targets.md` page rendered from them.

use crate::corpus::*;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// Roles every shape fills; `realtime` is optional.
pub const ROLES: [(&str, &str); 8] = [
    ("cron_tick", "cron tick"),
    ("reconciler", "reconciler"),
    ("orchestrator", "durable orchestrator"),
    ("catalog", "single-writer catalog"),
    ("object_store", "object store"),
    ("query_face", "hot-path query face"),
    ("compute", "heavy compute"),
    ("secrets", "secrets"),
];

#[derive(Deserialize, Debug)]
pub struct Target {
    pub provider: String,
    pub title: String,
    #[serde(default)]
    pub serves: String,
    #[serde(default)]
    pub shape: Vec<Shape>,
}

#[derive(Deserialize, Debug)]
pub struct Shape {
    pub name: String,
    #[serde(default)]
    pub default: bool,
    pub kind: String,
    #[serde(default)]
    pub profiles: Vec<String>,
    #[serde(default)]
    pub wall_clock_cap_min: Option<i64>,
    #[serde(default)]
    pub excludes: Vec<String>,
    #[serde(default)]
    pub roles: BTreeMap<String, String>,
}

/// Every target file under `spec/targets/`, sorted by file name, with load errors.
pub fn load(c: &Corpus) -> (Vec<(String, Target)>, Vec<Finding>) {
    let mut out = Vec::new();
    let mut errs = Vec::new();
    let dir = c.root.join("spec/targets");
    let mut files: Vec<_> = std::fs::read_dir(&dir).into_iter().flatten().flatten().map(|e| e.path()).collect();
    files.sort();
    for p in files.into_iter().filter(|p| p.extension().map(|x| x == "toml").unwrap_or(false)) {
        let rel = format!("spec/targets/{}", p.file_name().unwrap().to_string_lossy());
        match std::fs::read_to_string(&p).map_err(|e| e.to_string()).and_then(|s| toml::from_str::<Target>(&s).map_err(|e| e.to_string())) {
            Ok(t) => out.push((rel, t)),
            Err(e) => errs.push(Finding::new("targets", &rel, 0, "SpecTargetIncomplete", e.replace('\n', " "))),
        }
    }
    (out, errs)
}

/// The per-invocation wall clock at or below which a shape records both exclusions,
/// read from the `topology` fragment so the number has one home.
fn cap_bound(c: &Corpus) -> i64 {
    c.reg
        .fragments
        .get("topology")
        .and_then(|f| f.limit.get("topology-function-wall-clock"))
        .and_then(|l| l.value.as_integer())
        .unwrap_or(15)
}

pub fn check(c: &Corpus) -> Vec<Finding> {
    let (targets, mut out) = load(c);
    let cap = cap_bound(c);
    let f = |rel: &str, code: &str, msg: String| Finding::new("targets", rel, 0, code, msg);
    for (rel, t) in &targets {
        if t.shape.iter().filter(|s| s.default).count() != 1 {
            out.push(f(rel, "SpecTargetIncomplete", format!("`{}` marks {} shapes default, want 1", t.provider, t.shape.iter().filter(|s| s.default).count())));
        }
        for s in &t.shape {
            for (key, _) in ROLES {
                if s.roles.get(key).map(|v| v.trim().is_empty()).unwrap_or(true) {
                    out.push(f(rel, "SpecTargetIncomplete", format!("`{}` shape `{}` fills no `{key}` role", t.provider, s.name)));
                }
            }
            if s.wall_clock_cap_min.map(|m| m <= cap).unwrap_or(false) {
                for ex in ["first-time-backfill", "component-connector"] {
                    if !s.excludes.iter().any(|e| e == ex) {
                        out.push(f(rel, "SpecTargetCapUnrecorded", format!("`{}` shape `{}` caps at {} min and does not exclude `{ex}`", t.provider, s.name, s.wall_clock_cap_min.unwrap())));
                    }
                }
            }
            if s.kind == "function" && s.profiles.iter().any(|p| p != "edge") {
                out.push(f(rel, "SpecTargetFunctionProfile", format!("`{}` shape `{}` is function-class and lists profiles {:?}; a function-class shape hosts the edge profile alone", t.provider, s.name, s.profiles)));
            }
        }
    }
    out
}

/// `spec/targets.md`: per provider, a role table across its shapes and a diagram of its
/// default shape.
pub fn page(c: &Corpus) -> String {
    let (targets, _) = load(c);
    let mut s = String::new();
    s.push_str("# Deployment targets\n\nGenerated by `contextful-spec state` from `spec/targets/*.toml`; not authored.\n");
    s.push_str("`corpus.targets` in [`00-corpus.md`](./00-corpus.md) states the rules every target file obeys; `topology.deploy` in [`01-topology.md`](./01-topology.md) the roles they fill.\n");
    for (_, t) in &targets {
        let _ = write!(s, "\n## {}\n\n{}\n\n", t.title, t.serves);
        let _ = write!(s, "| Role |");
        for sh in &t.shape {
            let mark = if sh.default { " (default)" } else { "" };
            let _ = write!(s, " `{}`{mark} |", sh.name);
        }
        s.push_str("\n| --- |");
        for _ in &t.shape {
            s.push_str(" --- |");
        }
        s.push('\n');
        let mut rows: Vec<(&str, &str)> = ROLES.to_vec();
        rows.push(("realtime", "realtime run projection"));
        for (key, label) in rows {
            let _ = write!(s, "| {label} |");
            for sh in &t.shape {
                let _ = write!(s, " {} |", sh.roles.get(key).map(String::as_str).unwrap_or("—"));
            }
            s.push('\n');
        }
        let _ = write!(s, "| kind · profiles |");
        for sh in &t.shape {
            let _ = write!(s, " {} · {} |", sh.kind, sh.profiles.join(", "));
        }
        s.push('\n');
        let _ = write!(s, "| wall-clock cap · excluded |");
        for sh in &t.shape {
            let cap = sh.wall_clock_cap_min.map(|m| format!("{m} min")).unwrap_or_else(|| "none".into());
            let ex = if sh.excludes.is_empty() { "nothing".to_string() } else { sh.excludes.join(", ") };
            let _ = write!(s, " {cap} · {ex} |");
        }
        s.push('\n');
        if let Some(d) = t.shape.iter().find(|sh| sh.default) {
            // one node per role; the primitive filling it is the role table's cell
            let _ = write!(s, "\nThe `{}` shape; the table above names the primitive filling each role:\n\n```mermaid\nflowchart LR\n", d.name);
            let node = |id: &str, open: &str, close: &str, role: &str| format!("      {id}{open}\"{role}\"{close}\n");
            let role = |key: &str| -> &'static str { ROLES.iter().find(|(k, _)| *k == key).map(|(_, label)| *label).unwrap_or_default() };
            s.push_str("  CALLER([\"caller\"])\n");
            let _ = writeln!(s, "  subgraph ACCOUNT[\"deploying {} account\"]", t.title.replace('"', "'"));
            s.push_str("    subgraph CONTROL[\"control plane\"]\n");
            s.push_str(&node("TICK", "[", "]", role("cron_tick")));
            s.push_str(&node("REC", "[", "]", role("reconciler")));
            s.push_str(&node("ORCH", "[", "]", role("orchestrator")));
            s.push_str("    end\n    subgraph DATA[\"data plane\"]\n");
            s.push_str(&node("COMP", "[", "]", role("compute")));
            s.push_str(&node("QF", "[", "]", role("query_face")));
            s.push_str("    end\n    subgraph STATE[\"durable state\"]\n");
            s.push_str(&node("CAT", "[(", ")]", role("catalog")));
            s.push_str(&node("OBJ", "[(", ")]", role("object_store")));
            s.push_str("    end\n");
            s.push_str(&node("SEC", "[", "]", role("secrets")).replacen("      ", "    ", 1));
            s.push_str("  end\n");
            s.push_str("  TICK -- \"due tick\" --> REC -- \"dispatch a due unit\" --> ORCH -- \"run a step\" --> COMP\n");
            s.push_str("  COMP -- \"land parts + manifest\" --> OBJ\n");
            s.push_str("  REC & ORCH & COMP -- \"conditional write\" --> CAT\n");
            s.push_str("  CALLER -- \"query\" --> QF -- \"snapshot set\" --> OBJ\n");
            s.push_str("  QF -- \"catalog read\" --> CAT\n");
            s.push_str("  SEC -. \"credentials by reference\" .-> COMP\n");
            s.push_str("```\n");
        }
    }
    s
}
